### ISSUE TITLE
SmallIssue: TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by DryPreference** [DryPreference/LuCode#2]
This error occures when running the programm:
Welcome to Lucode Version 1.0 
To Exit type quit

Lucode_V1.0 --> 1+1
Traceback (most recent call last):
  File "c:/Users/G855912/Desktop/Lucode/shell.py", line 6, in <module>
    result, error = Lucode.run('<stdin>', text)
  File "c:\Users\G855912\Desktop\Lucode\Lucode.py", line 475, in run
    result = interpreter.visit(ast.node, context)
  File "c:\Users\G855912\Desktop\Lucode\Lucode.py", line 404, in visit
    return method(node, context)
  File "c:\Users\G855912\Desktop\Lucode\Lucode.py", line 417, in visit_BinOpNode
    left = res.register(self.visit(node.left_node, context))
  File "c:\Users\G855912\Desktop\Lucode\Lucode.py", line 404, in visit
    return method(node, context)
  File "c:\Users\G855912\Desktop\Lucode\Lucode.py", line 411, in visit_NumberNode
    Number(node.tok.value).set_context(context).set_pos(node.pos_start, node.pos_end)
TypeError: 'NoneType' object is not callable

**Comment by DryPreference** [comment]
This Problem has been solved by LS 

THE BUG FREE VERSION IS NOT PUSHED YET!!!

will push tonight
